### ISSUE TITLE
createTestingModule함수 확장 관련 고민 

### ISSUE THREAD

**Issue by seoko97** [JiPyoTak/plandar-server#24]
## 🐛 **버그 설명**

- Nest.js Test시 Guards 등 Decorator에 대한 확장이 닫혀있습니다.

## 🚦 **제시 혹은 요청하는 해결 방법**
- Nest.js 유저에 대한 인증을 수행할때 Guard를 통해 확인합니다.
- 이에 테스트를 진행하기 위해선 우선적으로 Guard 대한 overriding이 필요합니다.
- 해당 동작은 다음과 같습니다.
```ts
const mock_ForceFailGuard = { CanActivate: jest.fn(() => true) };

const app: TestingModule = await createTestingModule({
          controllers: [UserController],
      })
      .overrideProvider(ForceFailGuard).useValue(mock_ForceFailGuard)
```
- 하지만 `createTestingModule`함수는 이미 함수 내부에서 compile 함수가 실행되기 때문에 해당 함수에 대한 확장이 닫혀있습니다.

## 🚦 **제시 혹은 요청하는 해결 방법**
1. `createTestingModule` 함수 내부에 compile 메서드를 제거하여 확장 가능하게 변경
  - 각 테스트 파일에서 `createTestingModule` 함수사용시 compile 메서드를 실행해야 합니다.

## 🌄 **스크린샷**

<img width="512" alt="image" src="https://user-images.githubusercontent.com/60173534/226527112-ef84ef5b-84ea-4417-bb1d-df0997d3db5d.png">

- createTestingModule 함수는 compile 메소드를 통해 이미 완료되어 추가적인 확장을 정의할 수 없음

<br />

![image.jpg1](https://user-images.githubusercontent.com/60173534/226527507-2e0b4819-539f-4112-8233-8dabc6442879.png) |![image.jpg2](https://user-images.githubusercontent.com/60173534/226527380-dbad190f-0e8b-4907-9897-b7cb0f694da5.png)
--- | --- | 

-  왼쪽 이미지처럼 실행가능한 메서드들이 확인되어야 합니다.

**Comment by jintak0401** [comment]
이런 방식은 어떨까요?

```ts
...

// createTestingModule

export default async function createTestingModule(
  metadata: ModuleMetadata,
  callback?: (token: InjectionToken) => unknown,
  builderCb?: (builder: TestingModuleBuilder) => unknown,
) {
  callback = callback ?? (() => undefined);
  const moduleMocker = new ModuleMocker(global);

  const testingModuleBuilder = Test.createTestingModule(metadata)
    .useMocker((token) => {
      ...
    });

  if (builderCb) {
    builderCb(testingModuleBuilder)
  }
  return await testingModuleBuilder.compile();
}

// 사용

const mock_ForceFailGuard = { CanActivate: jest.fn(() => true) };

const app: TestingModule = await createTestingModule({
          controllers: [UserController],
      },
      undefined,
      (builder:  TestingModuleBuilder) => {
        builder.overrideProvider(ForceFailGuard).useValue(mock_ForceFailGuard);
      });
)
```

**Comment by pyo-sh** [comment]
테스팅 모듈에서 추가적인 확장 문제가 있을 줄은 몰랐네요..!
1. `createTestingModule`함수가 `compile` 함수를 실행하지 않고 TestingModuleBuilder 를 반환하거나
2. 모든 callback 함수를 실행하는 prop 받기
둘 중 하나가 고민이였을 텐데 2번으로 해결하셨군요!
저도 좋은 방법이라고 생각합니다 😃
